[package]
name = "oxs-derive"
version = "0.1.0"
authors = ["Daniel Wanner <daniel.wanner@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "oxs_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
